package com.niafikra;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qude' at '10/4/16 7:28 PM' with Gradle 2.13
 *
 * @author qude, @date 10/4/16 7:28 PM
 */
import java.util.Date;

public class Starter {
    public static void main(String[] args) {
    
       System.out.println("Mambo Dunia");
    }


    
}
