import org.junit.Test;
import static org.junit.Assert.*;
import com.niafikra.Starter;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'qude' at '10/4/16 7:28 PM' with Gradle 2.13
 *
 * @author qude, @date 10/4/16 7:28 PM
 */
public class StarterTest {
    @Test public  void main() {
        Starter classUnderTest = new Starter();
        assertEquals("Mambo Dunia", "Mambo Dunia");
    }
}
